---
name: 'Studio Save Changes GitHub Action'
description: |
  GitHub Action for adding, committing, and pushing changes to a repository.
author: 'Cliffano Subagio'
branding:
  icon: 'save'
  color: 'black'
inputs:
  github_token:
    description: GitHub token
    type: string
    required: true
  git_user_name:
    description: Git user name
    type: string
    required: false
    default: pakkunbot
  git_user_email:
    description: Git user email
    type: string
    required: false
    default: blah+pakkun@cliffano.com
runs:
  using: 'composite'
  steps:
    - name: Set git user email
      shell: bash
      run: git config --global user.email "${{ inputs.git_user_email }}"
    - name: Set git user name
      shell: bash
      run: git config --global user.name "${{ inputs.git_user_name }}"
    - name: Add new files
      shell: bash
      run: git add -A || echo "Nothing to add"
    - name: Commit the changes
      shell: bash
      run: git commit -m "Save changes" || echo "Nothing to commit"
    - name: Push the changes to remote repository
      uses: ad-m/github-push-action@v1.0.0
      with:
        tags: true
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
