name: Example Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Use Local Action
        uses: ./
        with:
          message: 'Save changes'
          push_changes: 'false'
      - name: Use Remote Action
        uses: cliffano/save-changes-action@main
        with:
          message: 'Save changes'
          push_changes: 'false'
